services:
  - type: web
    name: keyshield-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn appphishing:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_PASSWORD
        value: [YOUR_PASSWORD]  # Replace with your actual password
      - key: DOMAIN
        value: https://keyshield.my
      - key: DEBUG
        value: false
