services:
  - type: web
    name: keyshield-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn appphishing:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      
      - key: DB_HOST
        value: db.ezsqvlwxqiwewidquvwp.supabase.co
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: Harris@2005
      - key: DB_NAME
        value: postgres
      - key: DB_PORT
        value: 5432
